name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip' # Activa el caché de pip para compilar más rápido

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install httpx pytest anyio

    - name: Run Pytest
      env:
        PYTHONPATH: "." # Asegura que Python reconozca la carpeta 'app' desde la raíz
      run: |
        # Definir variable de entorno falsas para que pydantic-settings no falle en CI si las busca obligatorias
        export API_SECRET_KEY="test_key"
        export SLACK_WEBHOOK_URL="http://test.local"
        export PG_PASSWORD="test_password"
        pytest tests/
